### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 10000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 10000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "5535df9fb7fd4a8faff5af71696a2a8a",
  "accountNumber": "1000000002",
  "amount": 10000
}

### query transaction
GET http://localhost:8080/transaction/f52b29acc36543089d36659c8e71314b